#!/usr/bin/env python3
r"""Ship the dozen Bootstrap Icons the site uses instead of all 2078 of them.

Quarto bundles Bootstrap Icons as a 176 KB `.woff` plus a 97 KB stylesheet that
names every glyph in the set. Fonts are already compressed, so gzip does not
touch the `.woff`: those 176 KB cross the wire in full, on every page, and they
were the single largest download on the site — larger than either Bootstrap
bundle, larger than KaTeX. The site draws twelve icons.

So `fonts/bootstrap-icons-subset.woff2` carries those twelve, cut from Quarto's
own file, and this script swaps it in after each render. Same font, same glyph
outlines, same metrics — nothing about the rendering changes, there is just far
less of it.

    python3 tools/icon_subset.py           # post-render: swap the subset in
    python3 tools/icon_subset.py --build   # regenerate the subset (needs fontTools)

Which glyphs are needed is never written down by hand. Both modes rediscover it
from the rendered site, because the answer arrives from three unrelated places:

  * `bi-<name>` classes in the HTML Quarto generates,
  * `bi-<name>` classes that Quarto's own JavaScript adds at runtime,
  * bare `\\f5a1`-style codepoints in the compiled CSS, which is how
    `theme-common.scss` sets the sun and moon on the theme switch.

If the site ever needs a glyph the subset does not carry, the swap is skipped
and Quarto's full font is left in place. A heavier page is a far better failure
than a missing icon, and the warning says exactly how to fix it.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import shutil
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SITE = REPO / "_site"
SUBSET_WOFF2 = REPO / "fonts" / "bootstrap-icons-subset.woff2"
SUBSET_CSS = REPO / "fonts" / "bootstrap-icons-subset.css"
BOOTSTRAP_DIR = "site_libs/bootstrap"

# Assembled at runtime as `bi-${icon}`, so no scan of the source can see it:
# quarto-search.js stamps this on every result row in the search dropdown.
EXTRA_NAMES = {"file-richtext"}

# Bootstrap Icons live in the Private Use Area. Anything a stylesheet emits from
# that range through `content:` is a glyph request, whatever route it took.
PUA = range(0xE000, 0xF900)

CLASS_RE = re.compile(r"\bbi-([a-z0-9-]+)")
DEFINITION_RE = re.compile(r"\.bi-([a-z0-9-]+)::before\s*\{\s*content:\s*\"\\([0-9a-fA-F]{4,6})\"")

CSS_HEADER = """/* Bootstrap Icons, cut down to the glyphs this site actually draws.
 *
 * Generated by tools/icon_subset.py from the font Quarto ships; do not edit by
 * hand. Bootstrap Icons is MIT licensed, © 2019-2024 The Bootstrap Authors.
 */
@font-face {
  font-family: "bootstrap-icons";
  font-display: block;
  src: url("./bootstrap-icons-subset.woff2") format("woff2");
}

.bi::before,
[class^="bi-"]::before,
[class*=" bi-"]::before {
  display: inline-block;
  font-family: bootstrap-icons !important;
  font-style: normal;
  font-weight: normal !important;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  vertical-align: -0.125em;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
"""


def read(path: pathlib.Path) -> str:
    """Text of a file, tolerating the odd stray byte in a vendored asset."""
    return path.read_text(errors="ignore")


def glyph_table(icons_css: str) -> dict[str, int]:
    """Map every icon name Bootstrap defines to its codepoint."""
    return {m.group(1): int(m.group(2), 16) for m in DEFINITION_RE.finditer(icons_css)}


def quarto_dist() -> pathlib.Path:
    """Where Quarto keeps its own Bootstrap Icons.

    Not `_site`: by the time this has run once, the copy there is the subset, and reading the twelve-glyph stylesheet as
    if it were the full catalogue is how a newly used icon would go unnoticed.

    During a render Quarto hands the answer over in the environment. Asking the binary is the path for `--build`, which
    a person runs from a shell.
    """
    share = os.environ.get("QUARTO_SHARE_PATH")
    if not share:
        # Two lines, bin then share. Split on lines rather than whitespace: an
        # installation path may perfectly well contain a space.
        printed = subprocess.run(["quarto", "--paths"], capture_output=True, text=True, check=True).stdout
        share = [line for line in printed.splitlines() if line.strip()][-1]
    return pathlib.Path(share) / "formats/html/bootstrap/dist"


def rendered_html() -> bool:
    """Report whether the render that called this actually produced HTML.

    Quarto names what it has just written. On `quarto render --to pdf` that is one PDF, and nothing here has any
    business touching the HTML site left over from an earlier render. The list normally arrives in the environment, but
    `QUARTO_USE_FILE_FOR_PROJECT_OUTPUT_FILES` redirects it into a file — read both, or setting that flag would quietly
    restore the behaviour this exists to avoid. Outside a render neither is set, and then the caller means it.
    """
    listed = os.environ.get("QUARTO_PROJECT_OUTPUT_FILES")
    if listed is None:
        redirected = os.environ.get("QUARTO_USE_FILE_FOR_PROJECT_OUTPUT_FILES")
        if redirected and pathlib.Path(redirected).is_file():
            listed = pathlib.Path(redirected).read_text()
    return listed is None or any(f.endswith(".html") for f in listed.split())


def needed(site: pathlib.Path, table: dict[str, int]) -> dict[str, int]:
    """The glyphs the rendered site asks for, by whichever route it asks."""
    names: set[str] = set(EXTRA_NAMES)
    codepoints: set[int] = set()

    for page in site.rglob("*.html"):
        names |= set(CLASS_RE.findall(read(page)))
    for script in (site / "site_libs").rglob("*.js"):
        names |= set(CLASS_RE.findall(read(script)))
    for sheet in (site / "site_libs").rglob("*.css"):
        if sheet.name.startswith("bootstrap-icons"):
            continue  # the icon sheet names every glyph; that is not usage
        codepoints |= {ord(c) for c in read(sheet) if ord(c) in PUA}

    by_codepoint = {cp: name for name, cp in table.items()}
    found = {name: table[name] for name in names if name in table}
    found.update({by_codepoint[cp]: cp for cp in codepoints if cp in by_codepoint})
    return dict(sorted(found.items()))


def build(site: pathlib.Path) -> int:
    """Cut a fresh subset out of the font Quarto ships. Needs fontTools."""
    try:
        from fontTools import subset
        from fontTools.pens.boundsPen import BoundsPen
        from fontTools.ttLib import TTFont
    except ImportError:
        sys.exit("fontTools is not installed:  pip install 'fonttools[woff]' brotli")

    dist = quarto_dist()
    source_css, source_font = dist / "bootstrap-icons.css", dist / "bootstrap-icons.woff"
    if not source_font.exists():
        sys.exit(f"{source_font} is missing — is this the Quarto that renders the site?")
    if not (site / BOOTSTRAP_DIR).exists():
        sys.exit("no rendered site to read the used glyphs from — run `quarto render` first")

    table = glyph_table(read(source_css))
    wanted = needed(site, table)
    print(f"{len(wanted)} of {len(table)} glyphs are used:")
    for name, codepoint in wanted.items():
        print(f"    bi-{name:<32} U+{codepoint:04X}")

    font = TTFont(source_font)
    subsetter = subset.Subsetter(options=subset.Options(layout_features=[], notdef_outline=True))
    subsetter.populate(unicodes=wanted.values())
    subsetter.subset(font)

    # Bootstrap Icons ships every glyph with a left side bearing of 0 in `hmtx`
    # while the outlines themselves are inset — for seven of these twelve by as
    # much as 84 units in a 300-unit em. Rebuilding `glyf` reconciles the two by
    # moving the outline to meet the recorded bearing, which slides those icons
    # to the left edge of their box. Recording the bearing the outlines actually
    # have leaves them where they are. Costs eight bytes; caught by comparing
    # the rendered glyphs pixel for pixel against the full font.
    glyphs = font.getGlyphSet()
    for name in font.getGlyphOrder():
        pen = BoundsPen(glyphs)
        glyphs[name].draw(pen)
        advance, _ = font["hmtx"][name]
        font["hmtx"][name] = (advance, round(pen.bounds[0]) if pen.bounds else 0)

    font.flavor = "woff2"
    font.save(SUBSET_WOFF2)

    rules = "".join(f'\n.bi-{name}::before {{ content: "\\{codepoint:04x}"; }}' for name, codepoint in wanted.items())
    SUBSET_CSS.write_text(CSS_HEADER + rules + "\n")

    before = source_font.stat().st_size + source_css.stat().st_size
    after = SUBSET_WOFF2.stat().st_size + SUBSET_CSS.stat().st_size
    print(f"\n{before / 1024:.1f} KB -> {after / 1024:.1f} KB  ({(before - after) / 1024:.1f} KB saved per reader)")
    return 0


def restore(site: pathlib.Path, dist: pathlib.Path) -> None:
    """Put Quarto's own icon font back, whatever an earlier run left behind.

    The order is the point. A stylesheet always has to be pointing at a file that is already there, so the font is
    written first and the subset it replaces is removed last: interrupt this anywhere and the site still has a
    stylesheet and a font that agree with each other.
    """
    bootstrap = site / BOOTSTRAP_DIR
    shutil.copy2(dist / "bootstrap-icons.woff", bootstrap / "bootstrap-icons.woff")
    shutil.copy2(dist / "bootstrap-icons.css", bootstrap / "bootstrap-icons.css")
    (bootstrap / SUBSET_WOFF2.name).unlink(missing_ok=True)


def install(site: pathlib.Path) -> int:
    """Post-render: put the subset in place of Quarto's full icon font."""
    if not rendered_html():
        return 0  # this render produced no HTML; the site on disk is not ours to touch

    target_css = site / BOOTSTRAP_DIR / "bootstrap-icons.css"
    if not target_css.exists():
        return 0  # a format that does not use Bootstrap; nothing to do

    dist = quarto_dist()
    if not (SUBSET_WOFF2.exists() and SUBSET_CSS.exists()):
        print("icon_subset: no subset committed; restoring Quarto's own icon font", file=sys.stderr)
        restore(site, dist)
        return 0

    # The catalogue comes from Quarto rather than from `target_css`, which on
    # any render after the first is already the subset — reading the short list
    # as if it were the whole set is exactly how a newly used icon would slip
    # through the check below.
    wanted = needed(site, glyph_table(read(dist / "bootstrap-icons.css")))
    available = set(glyph_table(read(SUBSET_CSS)))
    missing = sorted(set(wanted) - available)
    if missing:
        # Not just "leave it alone": Quarto does not rewrite site_libs on an
        # incremental render, so what is sitting there may well be a previous
        # run's subset, and walking away would ship the page without the glyph.
        # Put the full font back and let the page be heavy but complete.
        print(
            "icon_subset: the subset has no glyph for "
            + ", ".join(f"bi-{name}" for name in missing)
            + "\n            restoring Quarto's full icon font — the page gets heavier, not wrong."
            + "\n            Regenerate with: python3 tools/icon_subset.py --build",
            file=sys.stderr,
        )
        restore(site, dist)
        return 0

    shutil.copy2(SUBSET_WOFF2, target_css.with_name(SUBSET_WOFF2.name))
    target_css.write_text(read(SUBSET_CSS))
    (site / BOOTSTRAP_DIR / "bootstrap-icons.woff").unlink(missing_ok=True)
    return 0


def main() -> int:
    """Swap the subset in, or rebuild it."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build", action="store_true", help="regenerate the subset from Quarto's font")
    parser.add_argument("--site", type=pathlib.Path, default=SITE, help="rendered site directory")
    args = parser.parse_args()
    return build(args.site) if args.build else install(args.site)


if __name__ == "__main__":
    raise SystemExit(main())
